<?php ?>

<div id="countriesCloud">
	<h2>Countries</h2>
	<ul id="countriesList"></ul>
</div>

<div id="seriesCloud">
	<h2>Series</h2>
	<ul id="seriesList"></ul>
</div>

<div id="mugsCloud">
	<h2>Mugs</h2>
	<ul id="mugsList"></ul>
</div>

<script type="text/javascript">  
// User panel initialization
// http://web-kreation.com/index.php/tutorials/nice-clean-sliding-login-panel-built-with-jquery/
jQuery(document).ready( function() {
	$("#panelOpenLink").click(function(){
		$("div#panel").slideDown("slow");
	});	
	
	$("#panelCloseLink").click(function(){
		$("div#panel").slideUp("slow");	
	});		

	$("#toggle a").click(function () {
		$("#toggle a").toggle();
	});
});
</script> 

<script type="text/javascript"> 
	$("#userSettings input").button();
</script>

<script type="text/javascript">
$(function() {
	// Настраиваем все элементы так, чтобы при выборе одного все остальные освобождались
	$('body').on('click', '#countriesList li', function() {
		$('#countriesCloud').data('selected', $(this).data('id'));
		ReloadSeries();
		ReloadMugs();
	});

	ReloadCountries();
	ReloadSeries();
	// We don't load mugs list on initialization because of it's length
});

function ReloadCountries() {	
	// Запрашиваем список стран с количествами кружек
    $.getJSON("api/countries", function(data) {
    	$('#countriesList').empty();
		$.each(data, function() { 
			var li = $("<li>");
			if ( 0 == $('#userSettings').length ) {
				// Пользователя нет - список обычный
				li.text(this.countryName);
				li.data('mugsCount', this.mugsCountryCount);
			} else {
				li.text(this.countryName + ' (' + this.mugsUserCount + '/' + this.mugsCountryCount + ')');
				li.data('mugsCount', this.mugsUserCount)
			}
			li.data('id', this.id);
			li.appendTo('#countriesList');
		});
		ResizeTags( $('#countriesList li') );
	});
}

function ReloadSeries() {	
	// Запрашиваем список стран с количествами кружек
    $.getJSON("api/series", function(data) {
    	$('#seriesList').empty();
		$.each(data, function() { 
			$("<li>").text(this.serieName)
					 .data('id', this.id)
					 .data('mugsCount', this.mugsCount)
					 .appendTo('#seriesList');  
		});
		ResizeTags( $('#seriesList li') );
	});
}	

function ReloadMugs() {
	var selectedCountry = $('#countriesCloud').data('selected') || '';

	// Запрашиваем список кружек
    $.getJSON('api/mugs', { countryId: selectedCountry }, function(data) {
    	$('#mugsList').empty();
		$.each(data, function() { 
			$("<li>").text(this.countryName + ' - ' + this.serieName + ' - ' + this.mugName)
					 .data('id', this.id)
					 .appendTo('#mugsList');  
		});
	});
}

function ResizeTags (li) {
	var countMin = 0, countMax = 0;
	var sizeMin = 1.0, sizeMax = 2.5;		// Размеры в .em в пропорции от кол-ва кружек
	
	$(li).each(function() {
		var intMugsCount = parseInt( $(this).data('mugsCount') );
		if ( intMugsCount > countMax ) { countMax = intMugsCount };
		if ( intMugsCount < countMin || countMin == 0 ) { countMin = intMugsCount };
	});
	
	if ( countMax > countMin ) {
		$(li).each(function() {
			var intMugsCount = parseInt( $(this).data('mugsCount') );
			var countProportion = (intMugsCount - countMin) / (countMax - countMin);
			var sizeNew = sizeMin + (sizeMax - sizeMin) * countProportion;
			$(this).animate( {fontSize: sizeNew + 'em'} );
		});
	};
}
</script> 
