<?php ?>

<script type="text/javascript" charset="utf-8"> 
	var aiSelectedRows = [];

	$(document).ready(function() {
		fnDatatableInit();
	} );

</script>

<script type="text/javascript" language="javascript" src="/js/dashboard.assets.datatable.js"></script>

<div class="ui-widget">
<table id="assetsTable" cellpadding="0" cellspacing="0" border="0" class="display">
	<thead>
		<tr>
			<th>#</th>
			<th>Наименование</th>
			<th>Класс</th>
			<th>Отрасль</th>
			<th>Имя ММВБ</th>
			<th>Код ММВБ</th>
            <th>Цвет</th>
		</tr>
	</thead>
</table>	  
</div>
