<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="description" content="Starbucks Collectible Mugs database and collection" />
<meta name="keywords" content="starbucks, mugs, collectibles, database, series" />

<title>Starbucks Mugs</title>
<script type="text/javascript" language="javascript" src="/js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery-ui.js"></script>
<script type="text/javascript" language="javascript" src="/js/common.js"></script>

<link rel="stylesheet" href="/css/redmond/jquery-ui.css" type="text/css" media="all" />
<link rel="stylesheet" href="/css/style.css" type="text/css" media="all" />
<link rel="stylesheet" href="/css/userpanel.css" type="text/css" media="all" />

<!-- PNG FIX for IE6 -->
<!-- http://24ways.org/2007/supersleight-transparent-png-in-ie6 -->
<!--[if lte IE 6]>
	<script type="text/javascript" src="js/pngfix/supersleight-min.js"></script>
<![endif]-->

</head>
<body>
<!-- Panel -->
<div id="toppanel">
<?php if ($this->auth->hasIdentity()) : ?>
	<div id="panel">
		<div class="content clearfix">
			<div class="left">
				<h1><?php echo $this->escape($this->auth->getIdentity()->userName); ?></h1>
<?php if ( isset($this->auth->getIdentity()->userAvatar) ) : ?>
				<img class="userAvatar" src="/images/avatars/<?php echo $this->escape($this->auth->getIdentity()->userAvatar); ?>" />
<?php else : ?>
				<img class="userAvatar" src="/images/noavatar.jpg" />
<?php endif; ?>
			</div>
			<div class="left">

			</div>
			<div class="left right">			

			</div>
		</div>
	</div> <!-- /login -->
	<!-- The tab on top -->	
	<div class="tab">
		<ul class="login">
			<li class="left">&nbsp;</li>
			<li>Hello,&nbsp;<?php echo $this->escape($this->auth->getIdentity()->userName); ?></li>
			<li class="sep">|</li>
			<li id="toggle">
				<a id="open" class="open" href="#">Open User panel</a>
				<a id="close" style="display: none;" class="close" href="#">Close panel</a>			
			</li>
			<li class="right">&nbsp;</li>
		</ul> 
	</div> <!-- / top -->
<?php else : ?>
	<div id="panel">
		<div class="content clearfix">
			<div class="left">
				<h1>Welcome to Starbucks Mugs Collections</h1>
				<h2>Sliding login panel Demo with jQuery</h2>		
				<p class="grey">You can put anything you want in this sliding panel: videos, audio, images, forms... The only limit is your imagination!</p>
				<h2>Download</h2>
				<p class="grey">To download this script go back to <a href="http://web-kreation.com/index.php/tutorials/nice-clean-sliding-login-panel-built-with-jquery" title="Download">article &raquo;</a></p>
			</div>
			<div class="left">
				<!-- Login Form -->
				<form class="clearfix" action="/users/login" method="post">
					<h1>Member Login</h1>
					<label class="grey" for="login">Username:</label>
					<input class="field" type="text" name="login" id="login" value="" size="23" />
					<label class="grey" for="password">Password:</label>
					<input class="field" type="password" name="password" id="password" size="23" />
	            	<label><input name="rememberme" id="rememberme" type="checkbox" checked="checked" value="forever" /> &nbsp;Remember me</label>
        			<div class="clear"></div>
					<input type="submit" name="submit" value="Login" class="bt_login" />
					<a class="lost-pwd" href="#">Lost your password?</a>
				</form>
			</div>
			<div class="left right">			
				<!-- Register Form -->
				<form action="#" method="post">
					<h1>Not a member yet? Sign Up!</h1>				
					<label class="grey" for="signup">Username:</label>
					<input class="field" type="text" name="signup" id="signup" value="" size="23" />
					<label class="grey" for="email">Email:</label>
					<input class="field" type="text" name="email" id="email" size="23" />
					<label>A password will be e-mailed to you.</label>
					<input type="submit" name="submit" value="Register" class="bt_register" />
				</form>
			</div>
		</div>
	</div> <!-- /login -->
	<!-- The tab on top -->	
	<div class="tab">
		<ul class="login">
			<li class="left">&nbsp;</li>
			<li>Hello Guest!</li>
			<li class="sep">|</li>
			<li id="toggle">
				<a id="open" class="open" href="#">Log In | Register</a>
				<a id="close" style="display: none;" class="close" href="#">Close Panel</a>			
			</li>
			<li class="right">&nbsp;</li>
		</ul> 
	</div> <!-- / top -->
<?php endif; ?>

</div> <!--panel -->
<div id="container">
	<div id="content">
<?php echo $this->layout()->content ?>
	</div><!-- / content -->		
</div><!-- / container -->
</body>
</html>
