<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Starbucks Mugs</title>
<script type="text/javascript" language="javascript" src="/js/jquery-1.7.1.min.js"></script> 
<script type="text/javascript" language="javascript" src="/js/jquery-ui.js"></script>
<link rel="stylesheet" href="/css/redmond/jquery-ui.css" type="text/css" media="all" /> 
</head>
<body style="font-size: 12px;">
	<p>Для доступа к сайту требуется авторизация</p>
</body>
</html>
