<?php ?>

<script type="text/javascript" charset="utf-8"> 
	var aiSelectedRows = [];

	$(document).ready(function() {
		fnDatatableInit();
	} );

</script>

<script type="text/javascript" language="javascript" src="/js/dashboard.quotes.datatable.js"></script>

<style type="text/css">
    .sf-right-aligned { text-align: right; }
    .sf-centered { text-align: center; }
</style>

<div class="ui-widget">
<table id="quotesTable" cellpadding="0" cellspacing="0" border="0" class="display">
	<thead>
		<tr>
			<th>#</th>
			<th>Наименование</th>
			<th>Котировка</th>
			<th>Момент</th>
			<th>Источник</th>
		</tr>
	</thead>
</table>	  
</div>
